### ISSUE TITLE
ABCKids guide missing

### ISSUE THREAD

**Issue by cantenna** [markcs/xml_tv#64]
Any reason why their is no guide information available for ABCKids?

**Comment by markcs** [comment]
Are you building your own xml file or getting it from xmltv.net?  Which region?

**Comment by Cantenna99** [comment]
Getting it from xmltv.net, Newcastle.

Going to try Sydney next.

odd, their is programing data avail 284791auepg.com.au (ABCKids)

Yet, it does not come across vi Xteve > Jellyfin, at first no data was shown then, ABC news programing data was displaying in ABCKids channel.

**Comment by Cantenna99** [comment]
Update: Sydney an issue as well

**Comment by Cantenna99** [comment]
Update 2: I reckon the formatting of the 284791auepg.com.au (ABCKids) may be the issue, in Jellyfin, I can bypass use of Xteve altogether and again, ABC Kids, no data shown despite correct mapping, All other channels, guides comes through just fine

**Comment by Cantenna99** [comment]
Logs from Jellyfin;

[2023-03-12 22:36:56.359 +00:00] [INF] [22] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Found epg channel in "XmlTV" null "ABCKids/TVPlus" "1007"
[2023-03-12 22:36:56.359 +00:00] [INF] [22] Emby.Server.Implementations.LiveTv.LiveTvManager: Refreshing guide with 7 days of guide data
[2023-03-12 22:36:56.359 +00:00] [DBG] [22] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Getting programs for channel "1007"-"ABCKids/TVPlus" from "XmlTV"-""
[2023-03-12 22:36:56.359 +00:00] [DBG] [22] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Getting xmltv programs for channel "1007"
[2023-03-12 22:36:56.359 +00:00] [INF] [22] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "http://172.3.0.2:34400/xmltv/xteve.xml"
[2023-03-12 22:36:56.359 +00:00] [DBG] [22] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Opening XmlTvReader for "/cache/xmltv/3461633b5d984af3a20bc689680817d1.xml"

[2023-03-12 22:36:56.436 +00:00] [ERR] [22] Emby.Server.Implementations.LiveTv.LiveTvManager: Error getting programs for channel "ABCKids/TVPlus"
Constraint: SQLitePCL.pretty.SQLiteException: NOT NULL constraint failed: ItemValues.Type
   at SQLitePCL.pretty.SQLiteException.Throw(Int32 rc, Int32 extended, String msg)
   at SQLitePCL.pretty.SQLiteException.CheckOk(sqlite3 db, Int32 rc)
   at SQLitePCL.pretty.StatementImpl.MoveNext()
   at Emby.Server.Implementations.Data.SqliteItemRepository.InsertItemValues(Byte[] idBlob, List`1 values, IDatabaseConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.UpdateItemValues(Guid itemId, List`1 values, IDatabaseConnection db)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItemsInTransaction(IDatabaseConnection db, IEnumerable`1 tuples)
   at SQLitePCL.pretty.DatabaseConnection.<>c__DisplayClass20_0.<RunInTransaction>b__0(IDatabaseConnection db)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction[T](IDatabaseConnection This, Func`2 f, TransactionMode mode)
   at SQLitePCL.pretty.DatabaseConnection.RunInTransaction(IDatabaseConnection This, Action`1 action, TransactionMode mode)
   at Emby.Server.Implementations.Data.SqliteItemRepository.SaveItems(IEnumerable`1 items, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Library.LibraryManager.CreateItems(IReadOnlyList`1 items, BaseItem parent, CancellationToken cancellationToken)
   at Emby.Server.Implementations.LiveTv.LiveTvManager.RefreshChannelsInternal(ILiveTvService service, IProgress`1 progress, CancellationToken cancellationToken)

**Comment by markcs** [comment]
This appears to be an issue on your side rather than the XML file.

I checked the xml using the Chrome Extension EPG Viewer (https://chrome.google.com/webstore/detail/lnhfllpjnichiepbkgnfhpaakhicbelh) and when downloading the Newcastle xml file from xmltv.net, the ABCKids channels are there.

![image](https://user-images.githubusercontent.com/2093916/224622465-c3a9b9a4-99f5-4fc6-840b-05863599e4c6.png)

**Comment by Cantenna99** [comment]
> This appears to be an issue on your side rather than the XML file.
> 
> I checked the xml using the Chrome Extension EPG Viewer (https://chrome.google.com/webstore/detail/lnhfllpjnichiepbkgnfhpaakhicbelh) and when downloading the Newcastle xml file from xmltv.net, the ABCKids channels are there.
> 
> ![image](https://user-images.githubusercontent.com/2093916/224622465-c3a9b9a4-99f5-4fc6-840b-05863599e4c6.png)

I've been at this all night, lol

Okay, see this log;

[2023-03-13 12:11:09.410 +00:00] [DBG] [28] Emby.Server.Implementations.LiveTv.LiveTvManager: Channel "ABCTV HD" has 71 new programs and 0 updated programs
[2023-03-13 12:11:09.510 +00:00] [DBG] [28] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Getting programs for channel "21"-"ABC TV" from "XmlTV"-""
[2023-03-13 12:11:09.510 +00:00] [DBG] [28] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Getting xmltv programs for channel "21"
[2023-03-13 12:11:09.510 +00:00] [INF] [28] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "http://172.3.0.2:34400/xmltv/xteve.xml"
[2023-03-13 12:11:09.510 +00:00] [DBG] [28] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Opening XmlTvReader for "/cache/xmltv/2b970b9e697441219466e7fc09045884.xml"
[2023-03-13 12:11:09.523 +00:00] [DBG] [28] Emby.Server.Implementations.LiveTv.LiveTvManager: Channel "ABC TV" has 71 new programs and 0 updated programs
[2023-03-13 12:11:09.576 +00:00] [DBG] [28] Emby.Server.Implementations.LiveTv.EmbyTV.EmbyTV: Getting programs for channel "22"-"ABCKids/TVPlus" from "XmlTV"-""
[2023-03-13 12:11:09.576 +00:00] [DBG] [28] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Getting xmltv programs for channel "22"
[2023-03-13 12:11:09.576 +00:00] [INF] [28] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: xmltv path: "http://172.3.0.2:34400/xmltv/xteve.xml"
[2023-03-13 12:11:09.576 +00:00] [DBG] [28] Emby.Server.Implementations.LiveTv.Listings.XmlTvListingsProvider: Opening XmlTvReader for "/cache/xmltv/2b970b9e697441219466e7fc09045884.xml"
[2023-03-13 12:11:09.596 +00:00] [DBG] [28] Emby.Server.Implementations.LiveTv.LiveTvManager: Channel "ABCKids/TVPlus" has 174 new programs and 0 updated programs
[2023-03-13 12:11:09.608 +00:00] [ERR] [28] Emby.Server.Implementations.LiveTv.LiveTvManager: Error getting programs for channel "ABCKids/TVPlus"
Constraint: SQLitePCL.pretty.SQLiteException: NOT NULL constraint failed: ItemValues.Type

You can see the ABC News channels come across just fine where the ABC Kids channel does not

**Comment by Cantenna99** [comment]
I suspect there is something wrong with the data for this particular channel, perhaps an incompatible formatting issue in one of the shows?

**Comment by Cantenna99** [comment]
Update; No I have programing guide data coming through for ABC Kids, but no data on all other channels!?

**Comment by markcs** [comment]
Could this be a Jellyfin issue? I don't use Jellyfin or xteve.

https://github.com/jellyfin/jellyfin/issues/8253

**Comment by cantenna** [comment]
Can confirm, the issue is indeed as you have discovered, all it takes is for one program to omit a category and the channel in its entirety will be omitted from Jellyfin.

Thank you for helping me sort this out.
